### ISSUE TITLE
How to walk through parsed string to get points

### ISSUE THREAD

**Issue by fils** [mb0/wkt#1]
Hello...
First..  thanks for this..  a WKT library is exactly what I need.  However, I am having a hard time seeing what to do at a point.  I have WKT string:

```
MULTIPOINT(2.9283 67.225,2.9283 67.225,2.93 67.22,2.93 67.22,2.93 67.22,1.0333 67.715,4.5767 66.6783,4.5767 66.6783)
```

using `geom, err := wkt.Parse([]byte(track))` where track is the above WKT string. 
 I can parse it and then a `log.Printf("GEOM: %v  \n\n", geom)`  
gives me

```
2016/02/18 14:35:08 GEOM: &{[{2.9283 67.225 0 0} {2.9283 67.225 0 0} {2.93 67.22 0 0} {2.93 67.22 0 0} {2.93 67.22 0 0} {1.0333 67.715 0 0} {4.5767 66.6783 0 0} {4.5767 66.6783 0 0}] 0}
```

Is this some way I can walk through these items so I can pull out the lat/longs and put them into a geojson file I am building with some other code?   I can't range on the type wkt.Geom object given it's a struct.  I am not even sure how the log is printing out the above points to be honest.  

any help would be much appreciated...

Thanks!
Doug

**Comment by mb0** [comment]
Geom is just the common interface implemented by the specific geometries in the package.
To access specific struct fields of the underlying Multipoint just type-assert it: 

```
    mp := geom.(*wkt.Multipoint)
    for _, coord := range mp.Coords {}
```

(code not tested) … or if you deal with multiple possible geometries use a type switch.

Start with [Effective Go](https://golang.org/doc/effective_go.html#interface_conversions) for more details on how interfaces work in Go.

Be aware though that the package was very quick little project i did for fun because someone asked for s.th. like it on the go-nuts mailing list years ago. It is not battle tested nor well supported by me (minimum wage serve job…). But looks pretty clean to me and it should be good base to extend in a fork or by pull requests.

Have fun!

**Comment by mb0** [comment]
Sorry :) it should be MultiPoint not Multipoint in the code example.

**Comment by fils** [comment]
Thanks!   I got it all working perfectly for me...  
Appreciate the help.

Interfaces have been a sector of Go I have not been able to understand to the level I know I should.  This small encounter with them has really helped me to see the light all of a sudden.  Thanks especially for that.  

I'll look over the reference you sent too and review them further.
